### ISSUE TITLE
Ignore FIXME

### ISSUE THREAD

**Issue by AlecRust** [bbugh/action-fixme-check#1]
Nice Action!

We have a `FIXME` in the code that we would like to keep. We have some custom Rubocop rules that look for comments and we'd like to include `FIXME` in one of these custom rules.

Have you considered adding a way to ignore a particular `FIXME`?

**Comment by bbugh** [comment]
Hi @AlecRust! 👋🏻

The purpose of the `FIXME`s are to block pull requests, and I think ignoring them would be counter to the feature. I usually use `TODO` for tasks that need to stay in the code base.

The matcher currently checks for `FIXME:` with a colon, you could write `FIXME` without the trailing colon and it won't be blocked.

Would either of those work for your case?

**Comment by AlecRust** [comment]
Thanks for quick response.

> `FIXME` without the trailing colon won't be blocked

This may help, thanks.

The `FIXME` in question is part of the linting code within our application. It's not a real `FIXME` that needs addressing.

**Comment by bbugh** [comment]
I hope that worked out for you, @AlecRust!
